PRAGMA foreign_keys = OFF;
BEGIN TRANSACTION;

DROP TABLE IF EXISTS M_SYSTEM;
CREATE TABLE M_SYSTEM (
    RENBAN INTEGER NOT NULL,
    WEB_SVC_URL TEXT,
    DEFAULT_CONTAINER_JYURYO INTEGER,
    DEFAULT_DUNNAGE_JYURYO INTEGER,
    DATA_CONF_YMDHMS TEXT,
    DATA_RECV_YMDHMS TEXT,
    UPDATE_PROC_NAME TEXT,
    UPDATE_YMD TEXT,
    PRIMARY KEY (RENBAN)
);

INSERT INTO M_SYSTEM (
    RENBAN,
    WEB_SVC_URL,
    DEFAULT_CONTAINER_JYURYO,
    DEFAULT_DUNNAGE_JYURYO
) VALUES (
    1,
    'http://scstestvanningreport.azurewebsites.net//websvc/svchandy.asmx',
    0,
    32
);

DROP TABLE IF EXISTS T_YOTEI;
CREATE TABLE T_YOTEI (
    BOOKING_NO TEXT NOT NULL,
    SAGYOU_YOTEI_YMD TEXT,
    CONTAINER_COUNT INTEGER,
    GOUKEI_BUNDLE INTEGER,
    GOUKEI_JYURYO INTEGER,
    KANRYO_CONTAINER INTEGER,
    KANRYO_BUNDLE INTEGER,
    KANRYO_JYURYO INTEGER,
    LAST_UPD_YMDHMS TEXT,
    INSERT_PROC_NAME TEXT,
    INSERT_YMD TEXT,
    UPDATE_PROC_NAME TEXT,
    UPDATE_YMD TEXT,
    PRIMARY KEY (BOOKING_NO)
);

DROP TABLE IF EXISTS T_SYUKKA_CONTAINER;
CREATE TABLE T_SYUKKA_CONTAINER (
    CONTAINER_ID INTEGER NOT NULL,
    SAGYOU_YOTEI_YMD TEXT,
    CONTAINER_NO TEXT,
    CONTAINER_JYURYO INTEGER,
    DUNNAGE_JYURYO INTEGER,
    SEAL_NO TEXT,
    DATA_SEND_YMDHMS TEXT,
    INSERT_PROC_NAME TEXT,
    INSERT_YMD TEXT,
    UPDATE_PROC_NAME TEXT,
    UPDATE_YMD TEXT,
    PRIMARY KEY (CONTAINER_ID)
);

DROP TABLE IF EXISTS T_SYUKKA_MEISAI;
CREATE TABLE T_SYUKKA_MEISAI (
    HEAT_NO TEXT NOT NULL,
    SOKUBAN TEXT NOT NULL,
    SYUKKA_SASHIZU_NO TEXT,
    BUNDLE_NO TEXT,
    JYURYO INTEGER,
    BOOKING_NO TEXT,
    CONTAINER_ID INTEGER,
    INSERT_PROC_NAME TEXT,
    INSERT_YMD TEXT,
    UPDATE_PROC_NAME TEXT,
    UPDATE_YMD TEXT,
    PRIMARY KEY (HEAT_NO, SOKUBAN)
);

DROP TABLE IF EXISTS W_SYUKKA_MEISAI;
CREATE TABLE W_SYUKKA_MEISAI (
    HEAT_NO TEXT NOT NULL,
    SOKUBAN TEXT NOT NULL,
    INSERT_PROC_NAME TEXT,
    INSERT_YMD TEXT,
    PRIMARY KEY (HEAT_NO, SOKUBAN)
);

DROP TABLE IF EXISTS T_KAKUNIN_CONTAINER;
CREATE TABLE T_KAKUNIN_CONTAINER (
    CONTAINER_ID TEXT NOT NULL,
    CONTAINER_NO TEXT,
    BUNDLE_CNT INTEGER,
    SAGYOU_YMD TEXT,
    CONTAINER_SYOUGO_KANRYO INTEGER,
    DATA_SEND_YMDHMS TEXT,
    INSERT_PROC_NAME TEXT,
    INSERT_YMD TEXT,
    UPDATE_PROC_NAME TEXT,
    UPDATE_YMD TEXT,
    PRIMARY KEY (CONTAINER_ID)
);

DROP TABLE IF EXISTS T_KAKUNIN_MEISAI;
CREATE TABLE T_KAKUNIN_MEISAI (
    HEAT_NO TEXT NOT NULL,
    SOKUBAN TEXT NOT NULL,
    SYUKKA_SASHIZU_NO TEXT,
    BUNDLE_NO TEXT,
    JYURYO INTEGER,
    CONTAINER_ID TEXT,
    CONTAINER_SYOUGO_KAKUNIN INTEGER,
    INSERT_PROC_NAME TEXT,
    INSERT_YMD TEXT,
    UPDATE_PROC_NAME TEXT,
    UPDATE_YMD TEXT,
    PRIMARY KEY (HEAT_NO, SOKUBAN)
);

DROP TABLE IF EXISTS W_KAKUNIN_MEISAI;
CREATE TABLE W_KAKUNIN_MEISAI (
    HEAT_NO TEXT NOT NULL,
    SOKUBAN TEXT NOT NULL,
    SYUKKA_SASHIZU_NO TEXT,
    BUNDLE_NO TEXT,
    JYURYO INTEGER,
    CONTAINER_ID TEXT,
    CONTAINER_SYOUGO_KAKUNIN INTEGER,
    INSERT_PROC_NAME TEXT,
    INSERT_YMD TEXT,
    UPDATE_PROC_NAME TEXT,
    UPDATE_YMD TEXT,
    PRIMARY KEY (HEAT_NO, SOKUBAN)
);

DROP TABLE IF EXISTS C_COMM_HISTORY;
CREATE TABLE C_COMM_HISTORY (
    LOG_ID TEXT NOT NULL,
    START_YMDHMS TEXT,
    END_YMDHMS TEXT,
    PROC_NAME TEXT,
    ARGUMENT TEXT,
    RETURN_VALUE TEXT,
    ERR_DESCRIPTION TEXT,
    PRIMARY KEY (LOG_ID)
);

PRAGMA user_version = 8;

COMMIT;
PRAGMA foreign_keys = ON;
